---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-application
  annotations:
    description: "This is the wisecow application"
    kubernetes.io/change-cause: "This is version 1"
  labels:
    app: wisecow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      name: testpod
      annotations:
        description: "This is testing pod"
      labels:
        app: wisecow
    spec:
      containers:
        - name: c00
          image: sahildahake/wisecow:latest
          ports:
            - containerPort: 4499
---
