---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-app
  annotations:
    description: "This is the wisecow application hosted on minikube cluster (Accuknox Assessment)"
    kubernetes.io/change-cause: "This is version 1"
  labels:
    app: wisecow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      name: wisecow-pod
      annotations:
        description: "This is production pod for wisecow application (Accuknox)"
      labels:
        app: wisecow
    spec:
      containers:
        - name: c00
          image: sahildahake/wisecow:latest
          ports:
            - containerPort: 4499
---
