---
apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
  annotations:
    description: "This is the wisecow-service for the assessment of (Accukno)"
  labels:
    app: wisecow
spec:
  selector:
    app: wisecow
  type: NodePort
  ports:
    - port: 100
      targetPort: 4499
      nodePort: 30001
---
