name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t sahildahake/wisecow:latest .
        docker push sahildahake/wisecow:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug: List files in workspace
      run: ls -al

    - name: Debug: Check for YAML files
      run: ls -al *.yml

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Copy manifests to VPS
      uses: appleboy/scp-action@v0.1.3
      with:
        source: "*.yml"
        target: ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/
        password: ${{ secrets.VPS_PASSWORD }}

    - name: Deploy to Kubernetes on VPS
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          kubectl apply -f /home/${{ secrets.VPS_USER }}/deployment.yml
          kubectl apply -f /home/${{ secrets.VPS_USER }}/service.yml
