name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker build -t sahildahake/wisecow:latest .
          docker push sahildahake/wisecow:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo apt-get update && sudo apt-get install -y openssh-client
            scp -r "*.yml" ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/sahil/
            kubectl apply -f /home/sahil/deployment.yml
            kubectl apply -f /home/sahil/service.yml
