name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker build -t sahildahake/wisecow:latest .
          docker push sahildahake/wisecow:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      # Transfer files to the remote server using scp with password authentication
      - name: Transfer files
        run: |
          echo "Transferring files..."
          sshpass -p "${{ secrets.VPS_PASSWORD }}" scp -o StrictHostKeyChecking=no deployment.yml service.yml ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/sahil/
      
      # Apply Kubernetes configurations using appleboy/ssh-action
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            echo "Files transferred, listing remote directory..."
            ls -la /home/sahil/ # Verify files are present
            echo "Applying Kubernetes configurations..."
            kubectl apply -f /home/sahil/deployment.yml && kubectl apply -f /home/sahil/service.yml
